# Generated by Django 3.1.2 on 2020-10-20 20:08

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oimage',
            name='Img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='images/'),
        ),
    ]
