# Generated by Django 3.1.2 on 2020-11-06 20:56

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0002_auto_20201020_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='oimage',
            name='action',
            field=models.CharField(choices=[('1', 'Remove'), ('2', 'Black'), ('3', 'Blur')], default='Black', max_length=100),
        ),
        migrations.AlterField(
            model_name='oimage',
            name='Img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, size=[1024, 768], upload_to='images/'),
        ),
    ]
