# Generated by Django 3.1.2 on 2020-11-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0004_auto_20201106_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oimage',
            old_name='Img',
            new_name='Image',
        ),
        migrations.AlterField(
            model_name='oimage',
            name='action',
            field=models.CharField(choices=[('1', 'Remove'), ('2', 'Blur'), ('3', 'Black and White')], default=3, max_length=100),
        ),
    ]
