# Generated by Django 3.1.2 on 2021-08-16 07:24

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, size=[1024, 768], upload_to='images/')),
                ('action', models.CharField(choices=[('1', 'Remove'), ('2', 'Blur'), ('3', 'Black and White')], default=3, max_length=100)),
            ],
        ),
    ]
